steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vcbl-chatbot:$COMMIT_SHA', '.']
  
  # 이미지를 Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vcbl-chatbot:$COMMIT_SHA']
  
  # Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'vcbl-chatbot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vcbl-chatbot:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'  # 서울 리전
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'DATABASE_URL=sqlite:///app/data/vcbl_chatbot.db'

images:
  - 'gcr.io/$PROJECT_ID/vcbl-chatbot:$COMMIT_SHA'
