# Cloud Build configuration for automatic deployment to Cloud Run
# Triggered by pushing to the main/master branch or manually

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vcbl-chatbot-repo/vcbl-chatbot:$COMMIT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vcbl-chatbot-repo/vcbl-chatbot:latest'
      - '.'
    id: 'build-image'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vcbl-chatbot-repo/vcbl-chatbot:$COMMIT_SHA'
    id: 'push-image-sha'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vcbl-chatbot-repo/vcbl-chatbot:latest'
    id: 'push-image-latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vcbl-chatbot'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vcbl-chatbot-repo/vcbl-chatbot:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--set-env-vars'
      - 'FLASK_ENV=production,PORT=8080,INIT_ADMIN_ON_START=true,ADMIN_STUDENT_ID=9999000001,ADMIN_NAME=Super Administrator,ADMIN_PASSWORD:ADMIN_PASSWORD:latest'
      - '--add-cloudsql-instances'
      - '${_CLOUD_SQL_INSTANCE}'
      - '--set-secrets'
      - 'SECRET_KEY=SECRET_KEY:latest,JWT_SECRET_KEY=JWT_SECRET_KEY:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,DATABASE_URL=DATABASE_URL:latest'
    id: 'deploy-cloud-run'

# Substitution variables (can be overridden in trigger settings)
substitutions:
  _REGION: 'asia-northeast3'  # Seoul region
  _MEMORY: '1Gi'
  _CPU: '1'
  _MIN_INSTANCES: '0'  # Scale to zero when not in use
  _MAX_INSTANCES: '10'
  _CLOUD_SQL_INSTANCE: 'PROJECT_ID:REGION:INSTANCE_NAME'  # Update this

# Images to be pushed to Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vcbl-chatbot-repo/vcbl-chatbot:$COMMIT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vcbl-chatbot-repo/vcbl-chatbot:latest'

# Build timeout (default is 10 minutes)
timeout: '1200s'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

