steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vcbl-chatbot:$COMMIT_SHA', '.']
  
  # 이미지를 Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vcbl-chatbot:$COMMIT_SHA']
  
  # 데이터베이스 마이그레이션 실행 (선택사항)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'execute'
      - 'vcbl-chatbot-migrate'
      - '--region'
      - 'asia-northeast3'
      - '--wait'
    allowFailure: true  # 마이그레이션 작업이 없으면 실패 허용
  
  # Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'vcbl-chatbot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vcbl-chatbot:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'  # 서울 리전
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      # 리소스 설정
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'  # 콜드 스타트 방지
      - '--max-instances'
      - '100'  # 다중 작업 처리
      - '--concurrency'
      - '80'  # 인스턴스당 동시 요청 수
      # Cloud SQL 연결
      - '--add-cloudsql-instances'
      - '${_CLOUD_SQL_INSTANCE}'
      # 환경 변수 설정
      - '--set-env-vars'
      - 'CLOUD_SQL_INSTANCE=${_CLOUD_SQL_INSTANCE},DB_USER=${_DB_USER},DB_NAME=${_DB_NAME},FLASK_ENV=production'
      # Secret Manager에서 비밀 가져오기
      - '--set-secrets'
      - 'SECRET_KEY=vcbl-secret-key:latest,JWT_SECRET_KEY=vcbl-jwt-secret-key:latest,DB_PASSWORD=vcbl-db-password:latest,OPENAI_API_KEY=vcbl-openai-api-key:latest,REDIS_URL=vcbl-redis-url:latest'
      # 서비스 계정
      - '--service-account'
      - 'vcbl-chatbot-sa@${PROJECT_ID}.iam.gserviceaccount.com'
      # 타임아웃 설정
      - '--timeout'
      - '300s'

# 치환 변수 (기본값)
substitutions:
  _CLOUD_SQL_INSTANCE: '${PROJECT_ID}:asia-northeast3:vcbl-postgres'
  _DB_USER: 'vcbl_user'
  _DB_NAME: 'vcbl_chatbot'

images:
  - 'gcr.io/$PROJECT_ID/vcbl-chatbot:$COMMIT_SHA'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
