gcloud run deploy vcbl-frontend `
  --source . `
  --dockerfile Dockerfile.frontend `
  --region asia-northeast3 `
  --allow-unauthenticated `
  --service-account vcbl-deployer@vcbl-project-2025.iam.gserviceaccount.com `
  --set-env-vars NODE_ENV=production `
  --set-env-vars VITE_API_URL="https://vcbl-backend-1048443259603.asia-northeast3.run.app" `
  --max-instances 3 `
  --cpu 1 `
  --memory 512Mi
