version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # SQLite 사용 (단순화)
      DATABASE_URL: sqlite:///app/data/vcbl_chatbot.db
      SECRET_KEY: dev-secret-key-change-in-production
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MODEL_NAME: gpt-4o-mini
      SUMMARY_TRIGGER_TOKENS: 3500
      MAX_TOKENS_PER_REQUEST: 4000
      MAX_TOKENS_OUTPUT: 1000
      DAILY_TOKEN_LIMIT: 50000
      PORT: 8080
    volumes:
      # SQLite 데이터베이스 파일을 영구 저장
      - ./data:/app/data

