version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: vcbl_chatbot
      POSTGRES_USER: vcbl
      POSTGRES_PASSWORD: vcbl_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vcbl"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://vcbl:vcbl_password@postgres:5432/vcbl_chatbot
      SECRET_KEY: dev-secret-key-change-in-production
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MODEL_NAME: gpt-4o-mini
      SUMMARY_TRIGGER_TOKENS: 3500
      MAX_TOKENS_PER_REQUEST: 4000
      MAX_TOKENS_OUTPUT: 1000
      DAILY_TOKEN_LIMIT: 50000
      PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:

