gcloud run jobs create vcbl-migrate `
  --image asia-northeast3-docker.pkg.dev/vcbl-project-2025/cloud-run-source-deploy/backend:latest `
  --region asia-northeast3 `
  --service-account vcbl-deployer@vcbl-project-2025.iam.gserviceaccount.com `
  --add-cloudsql-instances "vcbl-project-2025:asia-northeast3:vcbl-db" `
  --set-env-vars FLASK_ENV=production `
  --set-env-vars SECRET_KEY="4Q81R9YsTc0WqcNR1bTqqS0lzgPZFN-SeQRQ94VwQ-k" `
  --set-env-vars JWT_SECRET_KEY="gDekIiQJfUvgDPX22UndYtNVPOUAcrZcQX3wcP9oZqM" `
  --set-env-vars OPENAI_API_KEY="<OPENAI_API_KEY>" `
  --set-env-vars DB_USER="vcbl_user" `
  --set-env-vars DB_PASSWORD="vcblAdmin1234!" `
  --set-env-vars DB_NAME="vcbl_chatbot" `
  --set-env-vars CLOUD_SQL_INSTANCE="vcbl-project-2025:asia-northeast3:vcbl-db" `
  --cpu 1 `
  --memory 1Gi `
  --command "bash" `
  --args "/scripts/migrate-db.sh"
