"""make prompt_text nullable in scaffoldings

Revision ID: 6c73c5f85e19
Revises: 72ce3d649529
Create Date: 2025-10-13 20:24:12.019688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c73c5f85e19'
down_revision = '72ce3d649529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scaffoldings', schema=None) as batch_op:
        batch_op.alter_column('prompt_text',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('learning_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('learning_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('scaffoldings', schema=None) as batch_op:
        batch_op.alter_column('prompt_text',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
