"""add_survey_url_to_video

Revision ID: 72ce3d649529
Revises: 86216cd24f8a
Create Date: 2025-10-13 20:20:34.332350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ce3d649529'
down_revision = '86216cd24f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('survey_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('survey_url')
    # ### end Alembic commands ###
