"""add intro_text to video

Revision ID: 8e38bc70a178
Revises: 6c73c5f85e19
Create Date: 2025-10-13 20:38:37.819497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e38bc70a178'
down_revision = '6c73c5f85e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intro_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('intro_text')

    # ### end Alembic commands ###
