"""Initial migration

Revision ID: bc741a1ffa94
Revises: 
Create Date: 2025-10-14 14:14:51.283754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc741a1ffa94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('show_after_registration', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('daily_token_usage', sa.Integer(), nullable=True),
    sa.Column('total_token_usage', sa.Integer(), nullable=True),
    sa.Column('last_token_reset', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_student_id'), ['student_id'], unique=True)

    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('youtube_url', sa.String(length=500), nullable=False),
    sa.Column('youtube_id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('scaffolding_mode', sa.String(length=20), nullable=True, server_default='none'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('learning_enabled', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('survey_url', sa.String(length=500), nullable=True),
    sa.Column('intro_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint("scaffolding_mode IN ('none', 'prompt', 'chat')", name='ck_videos_scaffolding_mode')
    )
    op.create_table('chat_prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('user_role', sa.String(length=20), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_updated_at', sa.DateTime(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_video_id'), ['video_id'], unique=False)

    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_logs_video_id'), ['video_id'], unique=False)

    op.create_table('scaffoldings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scaffoldings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scaffoldings_video_id'), ['video_id'], unique=False)

    op.create_table('survey_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('scaffolding_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scaffolding_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scaffolding_id'], ['scaffoldings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scaffolding_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scaffolding_responses_scaffolding_id'), ['scaffolding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scaffolding_responses_user_id'), ['user_id'], unique=False)

    op.create_table('survey_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['survey_questions.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_id', 'question_id', 'user_id', name='unique_user_survey_question_response')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_responses')
    with op.batch_alter_table('scaffolding_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scaffolding_responses_user_id'))
        batch_op.drop_index(batch_op.f('ix_scaffolding_responses_scaffolding_id'))

    op.drop_table('scaffolding_responses')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    op.drop_table('survey_questions')
    with op.batch_alter_table('scaffoldings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scaffoldings_video_id'))

    op.drop_table('scaffoldings')
    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_logs_video_id'))
        batch_op.drop_index(batch_op.f('ix_event_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_event_logs_created_at'))

    op.drop_table('event_logs')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_video_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))

    op.drop_table('chat_sessions')
    op.drop_table('chat_prompt_templates')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint('ck_videos_scaffolding_mode', type_='check')
    op.drop_table('videos')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_student_id'))

    op.drop_table('users')
    op.drop_table('surveys')
    # ### end Alembic commands ###
